format_version: 10
pipelines:
  job:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-fe97972:
        git: https://github.com/saiyadaz/expense-ansible1.git
        shallow_clone: false
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash #bash ansible.sh frontend
                    run_if: passed

      - STAGE:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash #bash ansible.sh frontend
                    run_if: passed

      - PROD:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash #bash ansible.sh frontend
                    run_if: passed
