




- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/jobs/pipeline.xml') }}"
    name: test
    password: "{{secrets.jenkins_password}}"
    url: http://localhost:808
    user: "{{secrets.jenkins_user}}"
####change the URL in your URL-dns records